spring.application.name=trading-challenge-backend

# ============================================
# Server Configuration
# ============================================
server.port=8080
server.servlet.context-path=/api

# ============================================
# PostgreSQL Configuration
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_challenge
spring.datasource.username=postgres
spring.datasource.password=Password18182424$
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA/Hibernate Configuration
# ============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# Flyway Database Migrations
# ============================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.secret=trading_challenge_super_secret_key_that_is_minimum_256_bits_long_12345678901234567890
jwt.expiration=86400000

# ============================================
# Logging
# ============================================
logging.level.root=INFO
logging.level.com.mvp18=DEBUG


# Market Data
# Market Data
polygon.api.key=guFW5Wr0b2deM10yyR3DDhZdr22_cnlP
polygon.base.url=https://api.polygon.io
binance.base.url=https://api.binance.com
frankfurter.base.url=https://api.frankfurter.app
alphavantage.api.key= L3VXWTWEC0UJ9PBR
alphavantage.base.url=https://www.alphavantage.co